### PR TITLE
Configuration url

### LINKED ISSUE #50: clarify additional configuration info
> 41) Line 877: Leaf should probably renamed to reflect that is not a
    > configuration, but a location where the configuration is found.

### PR DESCRIPTION
**Pull request by mcr**
rename attribute.  close #50

### CODE REVIEW

**Comment by stfries** [comment]
BRSKI-PRM does not use this component of the voucher. So it should not provide problems as we look for known and used values of BRSKI-PRM. It is defined and used in BRSKI-Cloud and likely affects implementations using the component additional-configuration. 

In general as it is an optional value, the explaining text in RFC 8366bis should state "This node is optional because it is not used by all bootstrapping protocols." as for instance for the nonce leaf of the voucher.

While thinking about the naming, maybe "additional-manufacturer-configuration-uri" is more specific as the leaf description states the relation to the vendor/manufacturer. BTW, maybe it is better to call it manufacturer in the description instead of vendor.

Two further thoughts regarding this:

- In general in RFC8366bis there should be a statement that unknown values or leafs in the voucher or voucher request should be ignored by the implementation. 
- Nevertheless, the additional-configuration-url in general could also be interesting for BRSKI, BRSKI-PRM, or BRSKI-AE if it would be included in the registrar-voucher-request (as domain local URL) and populated in the voucher by the MASA. That way the pledge could get information where to find a configuration server in the registrar's domain. But this is just a thought. Maybe it is better to define such functionality via an additional leaf as the description of the additional-configuration-uri is set by the vendor/manufacturer (as stated in the description).

**Comment by mcr** [comment]
Oh, my mistake for thinking additional-configuration was from PRM!
BRSKI-Cloud. Oops.

**Review by upros — APPROVED** [review]
I'm good with this as is, but Steffen's comment about using term manufacturer instead of vendor seems ok too.

**Review by stfries — COMMENTED** [review]
The change in general is fine. What is open from my perspective are the following points:

- As it is an optional value, the explaining text in RFC 8366bis should state "This node is optional because it is not used by all bootstrapping protocols." as for instance for the nonce leaf of the voucher.
- Would a further optional value "additional-operator-configuration-uri" be beneficial to allow for populating a domain local configuration uri or mDNS name? In that case it would be good to rename the current "additional-configuration-uri" to "additional-manufacturer-configuration-uri"

**Comment by mcr** [comment]
stfries ***@***.***> wrote:
    > - As it is an optional value, the explaining text in RFC 8366bis should
    > state "This node is optional because it is not used by all
    > bootstrapping protocols." as for instance for the nonce leaf of the
    > voucher.

okay.

    > - Would a further optional value
    > "additional-operator-configuration-uri" be beneficial to allow for
    > populating a domain local configuration uri or mDNS name? In that case
    > it would be good to rename the current "additional-configuration-uri"
    > to "additional-manufacturer-configuration-uri"

Is this like DNS search path?

--
Michael Richardson ***@***.***>   . o O ( IPv6 IøT consulting )
           Sandelman Software Works Inc, Ottawa and Worldwide

**Comment by stfries** [comment]
Hi Michael,

It could be a DNS search path, an mDNS service name, or the actual URL to a domain local device management server. The latter will likely not really be used due to privacy reasons, but it could be an option. That way, no additional communication between registrar and pledge is necessary to communicate this information. If a mDNS service name is used, it could ease finding the device configuration in the customer domain.

Best regards
Steffen

**Pull request merged**
