### PR TITLE
Example appendix

### PR DESCRIPTION
**Pull request by mcr**
This ads an appendix with a single voucher example, expanded using asn1parse.

### CODE REVIEW

**Comment by kwatsen** [comment]
Let’s be sure to compare our asn1parse outputs.   Or, would you be okay if we just use my output?  ;)

K.

Sent from my iPhone

On Oct 25, 2017, at 9:54 PM, Michael Richardson <notifications@github.com<mailto:notifications@github.com>> wrote:


This ads an appendix with a single voucher example, expanded using asn1parse.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/anima-wg/voucher/pull/12

Commit Summary

  *   removed cms-contents
  *   added example keys and example voucher
  *   updated txt file

File Changes

  *   M Makefile<https://github.com/anima-wg/voucher/pull/12/files#diff-0> (6)
  *   D cms-contents.txt<https://github.com/anima-wg/voucher/pull/12/files#diff-1> (28)
  *   M draft-ietf-anima-voucher.txt<https://github.com/anima-wg/voucher/pull/12/files#diff-2> (80)
  *   M draft-ietf-anima-voucher.xml<https://github.com/anima-wg/voucher/pull/12/files#diff-3> (63)
  *   A examples/voucher_00-D0-E5-F2-00-02.asn1.txt<https://github.com/anima-wg/voucher/pull/12/files#diff-4> (129)
  *   A examples/voucher_00-D0-E5-F2-00-02.pkcs<https://github.com/anima-wg/voucher/pull/12/files#diff-5> (40)
  *   A keys/jrc_prime256v1.crt<https://github.com/anima-wg/voucher/pull/12/files#diff-6> (12)
  *   A keys/jrc_prime256v1.key<https://github.com/anima-wg/voucher/pull/12/files#diff-7> (5)
  *   A keys/masa_secp384r1.crt<https://github.com/anima-wg/voucher/pull/12/files#diff-8> (12)
  *   A keys/masa_secp384r1.key<https://github.com/anima-wg/voucher/pull/12/files#diff-9> (6)

Patch Links:

  *   https://github.com/anima-wg/voucher/pull/12.patch
  *   https://github.com/anima-wg/voucher/pull/12.diff

**Comment by kwatsen** [comment]
Kent Watsen <kwatsen@juniper.net> wrote:
    > Let’s be sure to compare our asn1parse outputs. Or, would you be okay
    > if we just use my output? ;)

I'm happy with whatever examples.
I just want some examples that I can validate and even reproduce.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by pritikin** [comment]
I like having an example and have no concerns about where the example comes from. 

I don't think we need/want the registrar certificate in there. If anything we'd want to see the "pinned-domain-cert" as the domain CA certificate. That way they could see how it ends up in the inner voucher format? 

From the voucher document the "registrar" entity isn't fully defined.

**Comment by mcr** [comment]
Max Pritikin <notifications@github.com> wrote:
    > I like having an example and have no concerns about where the example
    > comes from.

    > I don't think we need/want the registrar certificate in there.

Do you mean the owner/registrar private key?
That's what you don't think we need.   Fine with me.

I included it as I think that key is self-signed, so someone else could run
it through their code base to see if they generate an equivalent certificate.

    > anything we'd want to see the "pinned-domain-cert" as the domain CA
    > certificate. That way they could see how it ends up in the inner
    > voucher format?

Yes, so they need to see the owner's public key.

    > From the voucher document the "registrar" entity isn't fully defined.

okay, so we need to name things differently.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
I rebase this. We did not finish our conversation about this....

**Pull request closed without merging**
